#!/bin/bash
# Publish script for Hugo site with submodules
hugo && rsync -av public/ ./ && git add . && git commit -m "Update site content: publish Marathi article changes and remove rancher demo" && git push origin master

